<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [8]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
#reference - https://www.kite.com/python/answers/how-to-initialize-a-2d-array-in-python
def matrix_mul(A, B):
    # write your code
    row_count_A=len(A)
    col_count_A=len(A[0])

    row_count_B=len(B)
    col_count_B=len(B[0])
    if col_count_A!=row_count_B:
        print("Not Possible")
    else:
        l1=[]
        for i in range(row_count_A):
            lst=[]
            for j in range(col_count_B):
                
                prod=0
                for k in range(col_count_A):
                    prod+=A[i][k]*B[k][j]
                #print(prod)
                lst.append(prod)
            l1.append(lst)
        
        #printing result in matrix format
        #reference - https://stackoverflow.com/questions/13214809/pretty-print-2d-list
        print('\n'.join(['\t'.join([str(elem) for elem in mat_row]) for mat_row in l1]))
    

#Assumption 1 - The matrices are only 2 dimensional as it was mentioned that A and B are list of lists;
#Assumption 2 - Number of elements are maintained same in each and every row/column



#Input1
A1=[[1,3,4],[2,5,7],[5,9,6]]
B1=[[1,0,0,],[0,1,0],[0,0,1]]
print("A=",A1)
print("B=",B1)
print("A*B=")
matrix_mul(A1, B1)
print()

#Input2
A=[[1,2],[3,4]]
B=[[1,2,3,4,5],[5,6,7,8,9]]
print("A=",A)
print("B=",B)
print("A*B=")
matrix_mul(A, B)
print()


#Input3
A2=[[1,2],[3,4]]
B2=[[1,4],[5,6],[7,8],[9,6]]
print("A=",A2)
print("B=",B2)
print("A*B=")
matrix_mul(A2, B2)



A= [[1, 3, 4], [2, 5, 7], [5, 9, 6]]
B= [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
A*B=
1	3	4
2	5	7
5	9	6

A= [[1, 2], [3, 4]]
B= [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]
A*B=
11	14	17	20	23
23	30	37	44	51

A= [[1, 2], [3, 4]]
B= [[1, 4], [5, 6], [7, 8], [9, 6]]
A*B=
Not Possible


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [13]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    
    # your code here for picking an element from with the probability propotional to its magnitude
    #references - https://www.geeksforgeeks.org/sum-function-python/
    #https://www.w3schools.com/python/ref_random_uniform.asp
    #https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
    
    s=sum(A)
    B=[]
    C=[]
    for i in A:
        B.append(i/s)
    x=0
    for i in B:
        x+=i
        C.append(x)
    r=uniform(0,1)
    for i in range(0,len(C)):
        if r<=C[i]:
            return A[i]
A = [0,5,27,6,13,28,100,45,10,79]

    
def sampling_based_on_magnitude():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)
print("100 numbers selected randomly from A are below:")
sampling_based_on_magnitude()

100 numbers selected randomly from A are below:
79
79
79
100
79
100
79
100
45
79
100
79
79
28
100
28
28
79
28
6
100
79
45
45
100
100
27
28
45
79
5
27
79
79
79
79
79
27
27
100
100
100
100
100
45
45
100
27
45
45
5
79
28
79
28
45
100
28
27
28
100
28
79
27
6
28
79
10
100
79
100
45
13
79
45
100
79
45
79
79
100
100
27
27
100
27
79
6
100
10
27
45
79
27
6
45
79
100
28


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [32]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program

#references - https://stackoverflow.com/questions/5658369/how-to-input-a-regex-in-string-replace

#Approach
#step-1 removed '#' character 
#step 2 converted digits to #
#step 3 using findall got the list of #
#step 4 converted to string
#step 5 trimmed spaces

def replace_digits(String):
    #L=re.findall(r'[0-9]',String)
    S=re.sub('#',"", String)
    S=re.sub(r'[0-9]', "#", S)
    S=re.findall('#',S)
    L=" "
    L=L.join(S) 
    L=L.replace(" ","")
    return(L) # modified string after replacing the # with digits

String="234"
print("A =",String,"Output: ",replace_digits(String))

String1="a2b3c4"
print("A =",String1,"Output: ",replace_digits(String1))


String2="abc"
print("A =",String2,"Output: ",replace_digits(String2))

String3="#2a$#b%c%561#"
print("A =",String3,"Output: ",replace_digits(String3))


A = 234 Output:  ###
A = a2b3c4 Output:  ###
A = abc Output:  
A = #2a$#b%c%561# Output:  ####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [39]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
#reference - https://stackoverflow.com/questions/29216889/slicing-a-dictionary
#reference - https://www.geeksforgeeks.org/python-sort-python-dictionaries-by-key-or-value/

def display_dash_board(students, marks):
    l=len(students)
    stud_dict={}
    for i in range(0,l):
        stud_dict[students[i]]=marks[i]
        
    res=sorted(stud_dict.items(), key =lambda kv:(kv[1], kv[0]))
        
    # write code for computing top 5 students
    top_5_students =res[l-1:l-6:-1] # compute this
    # write code for computing top least 5 students
    least_5_students = res[0:5]# compute this
    # write code for computing top least 5 students
    maximum = res[-1][1]
    minimum = res[0][1]
    diff = maximum-minimum
    per_25 = diff*0.25
    pre_75 = diff*0.75
    d1={k:v for k,v in stud_dict.items() if v>=per_25 and v<=pre_75}
    students_within_25_and_75 = d1
    
    return top_5_students, least_5_students, students_within_25_and_75


students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

top_5_students, least_5_students, s = display_dash_board(students, marks)

students_within_25_and_75=sorted(s.items(), key =lambda kv:(kv[1], kv[0]))

print("a. Students who got top 5 ranks, in the descending order of marks")
for i in top_5_students:
    print(i[0],i[1])

print("b. Students who got least 5 ranks, in the increasing order of marks")
for i in least_5_students:
    print(i[0],i[1])

print("c. Students who got marks between >25th percentile <75th percentile, in the increasing order of marks")
for i in students_within_25_and_75:
    print(i[0],i[1])
   

a. Students who got top 5 ranks, in the descending order of marks
student8 98
student10 80
student2 78
student5 48
student7 47
b. Students who got least 5 ranks, in the increasing order of marks
student3 12
student4 14
student9 35
student6 43
student1 45
c. Students who got marks between >25th percentile <75th percentile, in the increasing order of marks
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [29]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure

#reference - https://learnandlearn.com/python-programming/python-reference/find-inverse-cosine-python
#reference -https://www.geeksforgeeks.org/python-math-function-sqrt/


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    cos_dist={}
    counter=0
    p,q=P
    for x,y in S:
        num=(x*p+y*q)#computing numerator
        den=(math.sqrt(x*x+y*y))*(math.sqrt(p*p+q*q))#computing denominator
        cos_dist[counter]=math.acos(num/den)#compute cosine distance
        counter+=1
    closest_points_to_p=sorted(cos_dist.items(), key =lambda kv:(kv[1], kv[0]))#sorting values based on distance    
    return(closest_points_to_p[0:5])

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print("The 5 closest points(based on cosine distance) in S from P are:")
for k,v in points:
    print(S[k])#print the returned values


The 5 closest points(based on cosine distance) in S from P are:
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [100]:
import re


def i_am_the_one(red,blue,line):
    sign=re.findall(r'[+,-]',line)
    s1=s2=1
    if sign[0]=='-':
        s1=-1
    if sign[1]=='-':
        s2=-1
             
    e=re.split(r'[+,-]', line)
    a=int(e[0][0:-1])
    b=int(e[1][0:-1])
    c=float(e[2])
   
    
    num_red_points=len(red)
    count_red_pos=0
    count_red_neg=0
    for r in red:
        s=a*r[0]+s1*b*r[1]+s2*c
        if s>0:
            count_red_pos+=1
        elif s<0:
            count_red_neg+=1
    if count_red_pos!=0 and count_red_neg!=0:
        return "NO"
    
    
    num_red_points=len(blue)
    count_blue_pos=0
    count_blue_neg=0
    for r in blue:
        s=a*r[0]+s1*b*r[1]+s2*c
        if s>0:
            count_blue_pos+=1
        elif s<0:
            count_blue_neg+=1
    if count_blue_pos!=0 and count_blue_neg!=0:
        return "NO"
    
    if (count_red_pos!=0 and count_blue_neg!=0) or (count_blue_pos!=0 and count_red_neg!=0):
        return "YES"
    else:
        return "NO"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [37]:
def curve_smoothing(string):
    # your code
    s=string.split(",")
    flag=0
    for x in range(0,len(s)):
        if s[x]=="_" and flag==0:
            i=x
            flag=1
        elif s[x]=="_":
            if x==len(s)-1:
                y=int(s[i-1])/(x-i+2)
                for a in range(i-1,x+1):
                    s[a]=y
                flag=0
            else:
                continue
        elif s[x]!="_" and flag==1:
            j=x
            
            if i==0:
                for a in range(i,j+1):
                    s[a]=int(s[j])/(j-i+1)
                flag=0
            else:
                z=i-1
                y=int(float(s[i-1])+float(s[j]))/(j-z+1)
                for a in range(z,j+1):
                    s[a]=y
                flag=0
            
    return(s)#list of values


Input1="_,_,_,24"
print("Input1: ",Input1)
smoothed_values= curve_smoothing(Input1)
print("Output1: ",smoothed_values)


Input2="40,_,_,_,60"
print("Input2: ",Input2)
smoothed_values= curve_smoothing(Input2)
print("Output2: ",smoothed_values)


Input3="80,_,_,_,_"
print("Input3: ",Input3)
smoothed_values= curve_smoothing(Input3)
print("Output3: ",smoothed_values)


Input4= "_,_,30,_,_,_,50,_,_"
print("Input4: ",Input4)
smoothed_values= curve_smoothing(Input4)
print("Output4: ",smoothed_values)

    

Input1:  _,_,_,24
Output1:  [6.0, 6.0, 6.0, 6.0]
Input2:  40,_,_,_,60
Output2:  [20.0, 20.0, 20.0, 20.0, 20.0]
Input3:  80,_,_,_,_
Output3:  [16.0, 16.0, 16.0, 16.0, 16.0]
Input4:  _,_,30,_,_,_,50,_,_
Output4:  [10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [39]:
def compute_conditional_probabilites(A):
    # your code - references - https://www.geeksforgeeks.org/python-count-occurrences-element-list/ and 
    #https://www.codegrepper.com/code-examples/python/python+get+second+column+of+list
    # print the output as per the instructions
    F=['F1','F2','F3','F4','F5']
    S=['S1','S2','S3']
    x=[]
    
    columns = list(zip(*A))
    S_List=columns[1]
    count_s=[0,0,0]
    for f in F:
        for s in S:
            x=f,s
            x=list(x)
            print("P(F={}|S=={})={}/{}".format(f,s,A.count(x),S_List.count(s)))
    
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F=F1|S==S1)=1/4
P(F=F1|S==S2)=1/3
P(F=F1|S==S3)=0/3
P(F=F2|S==S1)=1/4
P(F=F2|S==S2)=1/3
P(F=F2|S==S3)=1/3
P(F=F3|S==S1)=0/4
P(F=F3|S==S2)=1/3
P(F=F3|S==S3)=1/3
P(F=F4|S==S1)=1/4
P(F=F4|S==S2)=0/3
P(F=F4|S==S3)=1/3
P(F=F5|S==S1)=1/4
P(F=F5|S==S2)=0/3
P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [41]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(s1, s2):
    # your code
    #I am converting string to set
    S1=set(s1.split())
    S2=set(s2.split())
    b=set()
    c=set()
    #I am using set operations - intersection and difference
    a=len(S1&S2)    
    b1=S1.difference(S2)
    c1=S2.difference(S1)
    
    # since set is unordered, I am picking up values back from original string to retain order of words
    for x in s1.split():
        if x in b1:
            b.add(x)
            
    for y in s2.split():
        if y in c1:
            c.add(y)
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print("a.",a)
print("b.",b)
print("c.",c)

a. 7
b. {'first', 'F', '5'}
c. {'3', 'S', 'second'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [42]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure

#references - https://www.tutorialspoint.com/python3/number_log10.htm
import math
def compute_log_loss(A):
    # your code
    c=0
    n=len(A)
    for i in A:
        a=(i[0]*math.log10(i[1]))+((1-i[0])*math.log10(1-i[1]))
        c+=a
    c*=-1
    loss=c/n                                                          
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
print('Input',A)
loss = compute_log_loss(A)
print("Output: ",loss)

Input [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
Output:  0.42430993457031635
